import {mkdirSync as ensureTestDir} from 'node:fs';
ensureTestDir('test-results',{recursive:true});
import {chromium} from 'playwright';import fs from 'node:fs';
const b=await chromium.connectOverCDP('http://127.0.0.1:9333'),p=b.contexts()[0].pages()[0],errors=[];p.on('pageerror',e=>errors.push(e.message));const c=await p.context().newCDPSession(p);await c.send('Network.setCacheDisabled',{cacheDisabled:true});await p.reload();await p.waitForFunction(()=>window.game?.state==='menu',null,{timeout:60000});
const checks=[];function check(name,pass,detail){checks.push({name,pass:!!pass,detail});}
for(const mode of ['tdm','dom','ffa']){const r=await p.evaluate(async mode=>{await game.startGame('mp',{mode,map:'outpost',diff:0,allies:2,enemies:4,timeLimit:10,scoreLimit:100});game.renderer.setAnimationLoop(null);game.godMode=true;game.paused=false;const before=game.bots.map(b=>b.pos.clone());for(let i=0;i<180;i++)game.update(1/60,{mdx:0,mdy:0,streak:-1});return{map:game.world.def.id,bots:game.bots.length,moving:game.bots.filter((b,i)=>b.pos.distanceTo(before[i])>1).length,flags:game.mode.flags?.length||0,finite:game.bots.every(b=>b.pos.toArray().every(Number.isFinite))};},mode);check('海岸前哨模式 '+mode,r.map==='outpost'&&r.moving>=2&&r.finite&&(mode!=='dom'||r.flags===3),r);}
const campaign=await p.evaluate(async()=>{await game.startGame('campaign',{diff:0});game.renderer.setAnimationLoop(null);game.godMode=true;const g=game,m=g.mode,p=g.player,w=g.world,idle={mdx:0,mdy:0,streak:-1};g.paused=false;for(let i=0;i<5;i++)g.update(1/60,idle);const started={map:w.def.id,allies:m.allies.length,enemies:m.wave.length};for(const b of m.wave)b.takeDamage(1000,{attacker:p,weapon:'hk416'});g.update(1/60,idle);const s1=m.step;p.pos.copy(w.laptopPos);for(let i=0;i<185;i++)m.update(1/60,{...idle,interact:true});const s2=m.step;for(const b of m.wave)b.takeDamage(1000,{attacker:p,weapon:'hk416'});for(let i=0;i<46;i++)m.update(1,idle);const s3=m.step;p.pos.copy(w.lzPos);m.update(1/60,{...idle,interactPressed:true});return{started,s1,s2,s3,done:m.done,screen:g.menu.screen};});check('海岸前哨战役完整流程',campaign.started.map==='outpost'&&campaign.s1===1&&campaign.s2===2&&campaign.s3===3&&campaign.done&&campaign.screen==='results',campaign);
await p.evaluate(async()=>{game.exitToMenu();await game.startGame('mp',{mode:'tdm',map:'outpost',diff:0,allies:5,enemies:6,timeLimit:10,scoreLimit:100});game.godMode=true;game.paused=false;game.menu.hide();document.getElementById('clickToPlay').classList.add('hidden');game.player.pos.copy(game.world.navNearest(-12,7));game.player.yaw=-.8;game.renderer.setAnimationLoop(()=>game.frame());});await p.waitForTimeout(3000);
const fps=await p.evaluate(()=>new Promise(resolve=>{let count=0;const start=performance.now();function tick(now){count++;if(now-start>=5000)resolve({fps:count*1000/(now-start),quality:game.settings.quality,size:[game.canvas.width,game.canvas.height],drawCalls:game.renderer.info.render.calls,ao:game.ao.enabled});else requestAnimationFrame(tick);}requestAnimationFrame(tick);}));check('高画质性能',fps.fps>=45,fps);await p.screenshot({path:'test-results/奶蛙召唤-海岸前哨实机.png'});
await p.evaluate(()=>{game.renderer.setAnimationLoop(null);game.exitToMenu();game.menu.showLobby();});const cards=await p.locator('[data-map]').count();check('大厅仅显示海岸前哨',cards===1&&await p.locator('[data-map=outpost]').count()===1);await p.evaluate(()=>{game.menu.showMain();game.frame();});await p.screenshot({path:'test-results/奶蛙召唤-大厅.png'});
check('无运行时异常',!errors.length,errors);fs.writeFileSync('test-results/naiwa-outpost-full-tests.json',JSON.stringify({checks},null,2));console.log(JSON.stringify({checks},null,2));await b.close();if(checks.some(c=>!c.pass))process.exitCode=1;
